# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='end_time',
            field=models.CharField(default='9:00a.m.', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.CharField(default='12:00p.m.', max_length=10),
            preserve_default=False,
        ),
    ]
