# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160615_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='limit',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
