# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_class_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='taken',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
