# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='classes',
            field=models.ManyToManyField(blank=True, to='dashboard.Class'),
        ),
    ]
