# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_class_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='credit',
            new_name='credits',
        ),
    ]
