# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20160616_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
