# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_file_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
